targets:
  $default:
    builders:
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/app/router/router.dart
      json_serializable:
        generate_for:
          - lib/**/**.json.dart
        options:
          field_rename: snake
          create_to_json: false
      envied_generator:
        generate_for:
          - lib/app/env/env.dart
