name: Build apk

on:
  workflow_dispatch:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create .env file
        run: |
          echo "TMDB_TOKEN=$TMDB_SECRET" >> .env
          cat .env
          shell: bash
        env:
          TMDB_SECRET: ${{secrets.TMDB_TOKEN}}

      - name: Install dependencies
        run: flutter pub get
      - name: Run build runner
        run: dart run build_runner build
      - name: Analyze
        run: flutter analyze
      - name: Run test
        run: flutter test
      - name: Build apk
        run: flutter build apk
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
