name: Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - "feature/**"
      - "fix/**"
      - "tech/**"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create .env file
        run: |
          echo "TMDB_TOKEN=test" >> .env
          shell: bash
      - name: Install dependencies
        run: flutter pub get
      - name: Run build runner
        run: dart run build_runner build
      - name: Run test
        run: flutter test
